export const technologies = [
	"JavaScript",
	"TypeScript",
	"HTML",
	"CSS",
	"Styled Components",
	"CSS Modules",
	"Python",
	"C++",
	"React",
	"Next.JS",
	"Redux",
	"Redux Toolkit",
	"Django",
	"Node",
	"Express",
	"Webpack",
	"MongoDB",
	"Mongoose",
	"SQL",
	"MySql",
	"Sequelize",
	"PostgreSQL",
	"Firebase",
	"RT/Storage",
	"DB",
	"Cloud Functions",
	"Firebase SDK",
	"AWS",
	"Amplify",
	"Lambda",
	"CloudFront",
	"Agile Methodologies",
	"Scrum Development",
	"Debugging",
	"Unit Testing",
	"Performance Testing",
	"Docker",
	"Kubernetes",
	"UX Design",
	"Information Architecture",
	"Figma",
	"XD",
	"Photoshop",
	"Illustrator",
	"User Surveys",
	"Interviews",
	"Personas",
	"User Testing",
];